import { ReduxProvider } from "@/redux/provider";
import Head from "next/head";
import { Provider } from "react-redux";
import store from "@/store/redux";
import Nav from "./components/nav/nav";
import Footer from "./components/footer/footer";
import "./globals.css";

export const metadata = {
  title: {
    template: "%s | ArgentBank",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>
      <body>
        <ReduxProvider>
          <Nav />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
